# Generated by Django 5.2 on 2026-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('design', 'Design Tips'), ('maintenance', 'Maintenance'), ('trends', 'Trends 2026'), ('guide', 'Buying Guide')], default='guide', max_length=20),
        ),
    ]
